spec_version: 5.0.0
type: app

name: hello-app
title: Hello App
description: A basic Kelvin SmartApp template.
version: 1.0.0

flags:
  enable_runtime_update:
    configuration: false
    parameters: true
    resources: false
    resource_properties: true

data_streams:
  inputs: []
  outputs: []

control_changes:
  inputs: []
  outputs: []

custom_actions:
  inputs: []
  outputs: []

data_quality:
  inputs: []
  outputs: []

parameters: []

defaults:
  configuration: {}
  parameters: {}
  system: {}
